name: laser
channels:
  - defaults
  - conda-forge
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - ale-py=0.11.0=py311ha14e9d6_0
  - aom=3.9.1=he0c23c2_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.0=h91e5215_2
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - cudatoolkit=11.8.0=hd77b12b_0
  - dav1d=1.2.1=hcfcfb64_0
  - eigen=3.4.0=h477610d_1
  - expat=2.7.3=h885b0b7_4
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - ffmpeg=6.1.1=haa678a1_5
  - filelock=3.20.0=py311haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.10=h62dcd97_0
  - fsspec=2025.10.0=py311h4442805_0
  - gflags=2.2.2=he0c23c2_1005
  - giflib=5.2.2=h7edc060_0
  - glog=0.5.0=h4797de2_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py311h8598115_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=h1f81b68_0
  - gymnasium=1.2.2=np2py311ha3b8e51_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jax-jumpy=1.0.0=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9e=hcfcfb64_3
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.3.0=he916da2_2
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=20_win64_mkl
  - libcblas=3.9.0=20_win64_mkl
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=20_win64_mkl
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.12.0=haa95532_1
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.53=h7351971_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libtheora=1.2.0=habf309d_1
  - libtiff=4.7.1=h3a18249_0
  - libtorch=2.5.1=cpu_mkl_h9002858_104
  - libusb=1.0.29=h1839187_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=20.1.8=h29ce207_0
  - markupsafe=3.0.2=py311h827c3e9_0
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.0=py311h827c3e9_2
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - mysql-common=9.3.0=h2224204_0
  - mysql-libs=9.3.0=h809f9c2_0
  - networkx=3.5=py311haa95532_0
  - opencv=4.12.0=py311h6fcf9f4_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - opentelemetry-api=1.38.0=py311haa95532_0
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py311h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - py-opencv=4.12.0=haa95532_1
  - python=3.11.14=h981015d_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=cpu_mkl_py311h0452e45_104
  - qtbase=6.9.2=hd965823_2
  - rav1e=0.7.1=ha073cba_3
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.2.28=h5112557_0
  - setuptools=80.9.0=py311haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - sqlite=3.51.0=hda9a48d_0
  - svt-av1=3.1.2=hac47afa_0
  - sympy=1.14.0=py311haa95532_1
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - torchvision=0.20.1=cpu_py311h99a9fa7_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - absl-py==2.3.1
      - autorom==0.6.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.0
      - grpcio==1.76.0
      - hackatari==0.0.6
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - joblib==1.5.3
      - keyboard==0.13.5
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markdown==3.10
      - matplotlib==3.10.8
      - numpy==1.26.4
      - ocatari==2.2.1
      - packaging==25.0
      - pandas==2.3.3
      - protobuf==6.33.4
      - pyfiglet==1.0.4
      - pygame==2.6.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - six==1.17.0
      - stable-baselines3==2.7.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - tifffile==2025.12.20
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - tzdata==2025.3
      - urllib3==2.6.1
      - werkzeug==3.1.5
